import type { Metadata } from "next";
import "./globals.css";
import { Lato } from "next/font/google";
import SessionProvider from "./providers/session";
import { getServerSession } from "next-auth";
import { MoviesProvider } from "./providers/movies"; // Import the MoviesProvider

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = Lato({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-lato",
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en" className={`${lato.variable} `}>
      <body className="dark font-lato bg-zinc-950 text-white antialiased">
        <SessionProvider session={session}>
          <MoviesProvider > 
            {children}
          </MoviesProvider>
        </SessionProvider>
      </body>
    </html>
  );
}